- name: Create a the ingress
  k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    resource_definition: "{{ lookup('file', 'traefik.yml') }}"
    state: present
  run_once: true

- name: Create the app
  k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    resource_definition: "{{ lookup('file', 'whoami.yml') }}"
    state: present
  run_once: true